import { Schema, model, Document, Types } from 'mongoose';

export interface IFile extends Document {
  filename: string;      // Name of the file stored on the server (e.g., generated by multer)
  originalName: string;  // Original name of the file from the user
  mimeType: string;
  size: number;
  owner: Types.ObjectId; // Reference to the User who uploaded the file
  createdAt: Date;
  updatedAt: Date;
}

const FileSchema = new Schema<IFile>({
  filename: {
    type: String,
    required: true,
    trim: true,
  },
  originalName: {
    type: String,
    required: true,
    trim: true,
  },
  mimeType: {
    type: String,
    required: true,
    trim: true,
  },
  size: {
    type: Number,
    required: true,
  },
  owner: {
    type: Schema.Types.ObjectId,
    ref: 'User', // This creates a reference to the User model
    required: true,
  },
}, {
  timestamps: true // Automatically adds createdAt and updatedAt
});

const File = model<IFile>('File', FileSchema);

export default File;
